// <auto-generated />
using System;
using AnalyticsService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnalyticsService.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260106174828_models-added")]
    partial class modelsadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnalyticsService.Models.AppointmentSummary", b =>
                {
                    b.Property<Guid>("AppointmentSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CancelledCount")
                        .HasColumnType("int");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("NoShowCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalAppointments")
                        .HasColumnType("int");

                    b.HasKey("AppointmentSummaryId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("AppointmentSummaries");
                });

            modelBuilder.Entity("AnalyticsService.Models.DoctorUtilization", b =>
                {
                    b.Property<Guid>("DoctorUtilizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("UtilizationPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("DoctorUtilizationId");

                    b.HasIndex("DoctorId", "Date")
                        .IsUnique();

                    b.ToTable("DoctorUtilizations");
                });

            modelBuilder.Entity("AnalyticsService.Models.NoShowStatistic", b =>
                {
                    b.Property<Guid>("NoShowStatisticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("NoShowRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("NoShowStatisticId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("NoShowStatistics");
                });

            modelBuilder.Entity("AnalyticsService.Models.PeakHour", b =>
                {
                    b.Property<Guid>("PeakHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppointmentCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("HourOfDay")
                        .HasColumnType("int");

                    b.HasKey("PeakHourId");

                    b.HasIndex("Date", "HourOfDay")
                        .IsUnique();

                    b.ToTable("PeakHours");
                });

            modelBuilder.Entity("AnalyticsService.Models.WaitTimeMetric", b =>
                {
                    b.Property<Guid>("WaitTimeMetricId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AverageWaitTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("WaitTimeMetricId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("WaitTimeMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
